name: Test Docker image
on:
  workflow_dispatch:

jobs:
  test:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t mdbook:test .
